
import type { Document, User } from '../types';

// Initial documents to serve as fallback when the backend is unreachable.
export const initialDocuments: Document[] = [
  {
    id: 'doc-mock-1',
    name: 'Supply Agreement - ACME Corp.pdf',
    language: 'English',
    contractNo: 'CTR-2023-001',
    processedBy: 'Admin',
    processedDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(), // 2 days ago
    data: {
      contractNumber: 'CTR-2023-001',
      amendmentNumber: '0',
      partNumber: '123-456-789',
      partDescription: 'Plastic Injection Mold',
      clientName: 'ACME Corp',
      buyerNameAndAddress: 'ACME Corp, 123 Industrial Rd, Ohio',
      sellerNameAndAddress: 'Inteva Products',
      issueDate: '2023-01-15',
      effectiveDate: '2023-02-01',
      totalPrice: '50000',
      currency: 'USD',
      paymentTerms: 'Net 60',
      dunsNumber: '123456789',
      drawingNumber: 'DWG-001',
      manufacturingLocation: 'Troy, MI',
      shippingTo: 'Detroit, MI',
      sampleRequiredBy: '2023-03-01',
      buyerCode: 'ACM-001',
      accountManager: 'John Smith',
      purchasingContact: 'Jane Doe',
      manufacturingDunsNumber: '987654321',
      mailingAddressInformation: 'Same as Buyer',
      freightTerms: 'FOB',
      deliveryTerms: 'DDP',
      deliveryDuns: '112233445',
      shipFromDuns: '556677889',
      dailyCapacity: '1000',
      hoursPerDay: '8',
      containerType: 'Standard Box',
      receivingPlants: 'Plant A',
      basePrice: '50',
      unitOfMeasure: 'EA',
      reasonForIssuing: 'New Program',
      hazardousMaterialIndicator: 'No',
      language: 'English',
      originalLanguage: 'English',
      lessFinishPartNumber: '123-456',
      programName: 'Project X'
    }
  },
  {
      id: 'doc-mock-2',
      name: 'Amendment 1 - Beta Industries.docx',
      language: 'English',
      contractNo: 'CTR-2023-045',
      processedBy: 'Admin',
      processedDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(), // 5 days ago
      data: {
          contractNumber: 'CTR-2023-045',
          amendmentNumber: '1',
          partNumber: '987-654-321',
          partDescription: 'Steel Bracket',
          clientName: 'Beta Industries',
          buyerNameAndAddress: 'Beta Industries GmbH',
          sellerNameAndAddress: 'Inteva Products',
          issueDate: '2023-05-20',
          effectiveDate: '2023-06-01',
          totalPrice: '12500',
          currency: 'EUR',
          paymentTerms: 'Net 45',
          dunsNumber: '987654321',
          drawingNumber: 'DWG-002',
          manufacturingLocation: 'Germany',
          shippingTo: 'France',
          sampleRequiredBy: 'N/A',
          buyerCode: 'BET-002',
          accountManager: 'Hans Gruber',
          purchasingContact: 'N/A',
          manufacturingDunsNumber: 'N/A',
          mailingAddressInformation: 'N/A',
          freightTerms: 'Ex Works',
          deliveryTerms: 'N/A',
          deliveryDuns: 'N/A',
          shipFromDuns: 'N/A',
          dailyCapacity: '500',
          hoursPerDay: '16',
          containerType: 'Pallet',
          receivingPlants: 'Lyon',
          basePrice: '25',
          unitOfMeasure: 'EA',
          reasonForIssuing: 'Price Adjustment',
          hazardousMaterialIndicator: 'No',
          language: 'English',
          originalLanguage: 'English',
          lessFinishPartNumber: 'N/A',
          programName: 'Project Y'
      }
  },
  {
      id: 'doc-mock-3',
      name: 'Service Agreement - Gamma LLC.pdf',
      language: 'English',
      contractNo: 'CTR-2023-099',
      processedBy: 'Admin',
      processedDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 40).toISOString(), // 40 days ago
      data: {
          contractNumber: 'CTR-2023-099',
          amendmentNumber: '0',
          partNumber: 'N/A',
          partDescription: 'Consulting Services',
          clientName: 'Gamma LLC',
          buyerNameAndAddress: 'Gamma LLC',
          sellerNameAndAddress: 'Inteva Products',
          issueDate: '2023-08-10',
          effectiveDate: '2023-08-15',
          totalPrice: '5000',
          currency: 'USD',
          paymentTerms: 'Immediate',
          dunsNumber: '555555555',
          drawingNumber: 'N/A',
          manufacturingLocation: 'Remote',
          shippingTo: 'N/A',
          sampleRequiredBy: 'N/A',
          buyerCode: 'GAM-99',
          accountManager: 'N/A',
          purchasingContact: 'N/A',
          manufacturingDunsNumber: 'N/A',
          mailingAddressInformation: 'N/A',
          freightTerms: 'N/A',
          deliveryTerms: 'N/A',
          deliveryDuns: 'N/A',
          shipFromDuns: 'N/A',
          dailyCapacity: 'N/A',
          hoursPerDay: 'N/A',
          containerType: 'N/A',
          receivingPlants: 'N/A',
          basePrice: 'N/A',
          unitOfMeasure: 'HR',
          reasonForIssuing: 'New Service',
          hazardousMaterialIndicator: 'N/A',
          language: 'English',
          originalLanguage: 'English',
          lessFinishPartNumber: 'N/A',
          programName: 'Consulting'
      }
  }
];

export const initialUsers: User[] = [
  {
    id: 'user1',
    name: 'Admin',
    email: 'admin@domain.com',
    role: 'Admin',
    permissions: 'All Access',
  },
  {
    id: 'user2',
    name: 'Alice (Editor)',
    email: 'alice@domain.com',
    role: 'Editor',
    permissions: '3 contracts',
  },
  {
    id: 'user3',
    name: 'Bob (Viewer)',
    email: 'bob@domain.com',
    role: 'Viewer',
    permissions: '1 contracts',
  },
];
